# Generated by Django 4.0.dev20210713082503 on 2021-07-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='測試用的標題')),
                ('content', models.CharField(max_length=200, verbose_name='第一次嘗試寫的內容')),
            ],
        ),
    ]
