# Generated by Django 4.0.dev20210713082503 on 2021-08-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.TextField()),
                ('car_model', models.TextField()),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
